**จากแบบทดสอบ 9.4**

![img](../imgs/example9_4.png)

In [1]:
import numpy as np
import pandas as pd
from scipy import stats

In [2]:
O = np.array([0,28,32,35,20,10,0])
X_l = np.array([-np.inf,44.95,46.95,48.95,50.95,52.95,54.95])
X_r = np.array([44.95,46.95,48.95,50.95,52.95,54.95,np.inf])
x = (X_l+X_r)/2
x

array([ -inf, 45.95, 47.95, 49.95, 51.95, 53.95,   inf])

\
***หาค่าเฉลี่ย x_bar:***

In [3]:
x_bar = sum(O[1:-1]*x[1:-1])/125
x_bar

49.182

ทำไมต้องใช้ index 1:-1 ?

In [ ]:
sum(O*x)/125

<ipython-input-4-0541b337a504>:1: RuntimeWarning: invalid value encountered in multiply
  sum(O*x)/125


nan

In [ ]:
0*np.inf

nan

\
***หาค่าส่วนเบี่ยงเบนมาตราฐาน s:***

In [4]:
s = np.sqrt(sum(O[1:-1]*(x[1:-1]-x_bar)**2 )/(125-1))
s

2.4466435204436774

![img](../imgs/table_9_4_2.png)

\
***หาค่า P(Z):***

![img](../imgs/table_9_4_1.png)

In [5]:
z_l = (X_l-x_bar)/s
z_r = (X_r-x_bar)/s
PZ = stats.norm.cdf(z_r)-stats.norm.cdf(z_l)
PZ

array([0.04184046, 0.13897279, 0.28141415, 0.30281673, 0.17318412,
       0.05257292, 0.00919884])

\
***พิจารณา P(Z) ที่ชั้นแรก:***

In [6]:
PZ[0]

0.041840457456473

In [7]:
z_r[0], z_l[0]

(-1.729716636133638, -inf)

In [8]:
stats.norm.cdf(z_r[0])

0.041840457456473

In [9]:
stats.norm.cdf(z_l[0])

0.0

\
***พิจารณา หา P(Z) ที่ชั้นสุดท้าย:***

In [10]:
PZ[-1]

0.009198843844202442

In [11]:
z_r[-1], z_l[-1]

(inf, 2.3575154908362066)

In [ ]:
stats.norm.cdf(z_r[-1])

1.0

In [ ]:
stats.norm.cdf(z_l[-1])

0.9908011561557976

\
***หาค่า E:***

![img](../imgs/table_9_4_3.png)

In [12]:
E = 125*PZ
E

array([ 5.23005718, 17.37159856, 35.17676889, 37.85209069, 21.64801473,
        6.57161447,  1.14985548])

\
***รวมชั้นที่มีค่า E < 5 เข้ากับชั้นใกล้เคียง:***

In [13]:
E_adj = np.append(E[0:-2], E[-1]+E[-2])
O_adj = np.append(O[0:-2], O[-1]+O[-2])

In [14]:
E_adj

array([ 5.23005718, 17.37159856, 35.17676889, 37.85209069, 21.64801473,
        7.72146995])

In [15]:
O_adj

array([ 0, 28, 32, 35, 20, 10])

\
***หาค่า chi2_cal:***

In [16]:
chi2_cal = sum((O_adj-E_adj)**2/E_adj)
chi2_cal

13.032414699934208

\
***หาค่า chi2_crit:***

In [17]:
v = 6 - 2 - 1
v

3

In [18]:
chi2_crit = stats.chi2.isf(0.05,df=v)
chi2_crit

7.814727903251178

chi2_cal อยู่ในบริเวณวิกฤต ดังนั้นจึงต้องปฏิเสธ H0 และยอมรับ H1 คือ ข้อมูลความยาวของทารกแรกเกิดไม่ได้มีการแจกแจงแบบปกติ

\
***หาค่า p-value:***

In [ ]:
p_val = stats.chi2.sf(chi2_cal, df = 3)
p_val

0.004567028584983044

p-value < 0.05 จึง ต้องปฏิเสธ H0 และยอมรับ H1 คือ ข้อมูลความยาวของทารกแรกเกิดไม่ได้มีการแจกแจงแบบปกติ


\
***ใช้ฟังก์ชันลัดจาก library scipy.chisquare:***

In [ ]:
chi2_cal, p_val = stats.chisquare(f_obs=O_adj,
                                  f_exp=E_adj,
                                  ddof=2)

In [ ]:
chi2_cal, p_val

(13.032414699934208, 0.004567028584983044)